--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/7TogkGamemodeUI
build-by-default: true
branches:
- main
projects:
  7TogkGamemodeUI:
    path: ""
    icon: "icon.png"
    libs: 
      - src: https://poggit.pmmp.io/ci/Infernus101/FormAPI/libFormAPI
...
