### [ 7TogkGamemodeUI By Angga7Togk ] ###
##                                     ##
#                                       #

# use ยง to change colors
# use \n to create new line

### [ GAME MODE UI ] ###
##                    ##
#                      #

title: "ยงl7TogkGamemodeUI"

content: "Change in config.yml!"

